# Generated by Django 2.1.5 on 2019-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='股票代码')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='预测开始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='预测结束时间')),
                ('times', models.IntegerField(default=0, verbose_name='预测次数')),
                ('success', models.IntegerField(default=0, verbose_name='预测正确次数')),
                ('failed', models.IntegerField(default=0, verbose_name='预测错误次数')),
                ('status', models.IntegerField(choices=[(0, '预测涨'), (1, '预测跌'), (2, '无法预测')], default=0, verbose_name='预测结论')),
            ],
            options={
                'verbose_name': '趋势分析',
                'verbose_name_plural': '趋势分析',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], verbose_name='性别')),
                ('profession', models.CharField(max_length=128, verbose_name='职业')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ')),
                ('phone', models.CharField(max_length=128, verbose_name='电话')),
                ('homephone', models.CharField(max_length=128, null=True, verbose_name='家庭电话')),
                ('status', models.IntegerField(choices=[(0, '申请'), (1, '通过'), (2, '拒绝')], default=0, verbose_name='审核状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生管理系统',
                'verbose_name_plural': '学生管理系统',
            },
        ),
    ]
