# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0002_auto_20190426_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='代码')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='分析开始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='分析结束时间')),
                ('status', models.IntegerField(choices=[(0, '分析中'), (1, '分析完成')], default=0, verbose_name='分析状态')),
            ],
            options={
                'verbose_name': '趋势分析任务',
                'verbose_name_plural': '趋势分析任务',
            },
        ),
        migrations.CreateModel(
            name='AnalizeRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='代码')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='预测开始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='预测结束时间')),
                ('times', models.IntegerField(default=0, verbose_name='预测次数')),
                ('success', models.IntegerField(default=0, verbose_name='预测正确次数')),
                ('failed', models.IntegerField(default=0, verbose_name='预测错误次数')),
                ('result', models.IntegerField(choices=[(0, '向上'), (1, '向下'), (2, '无法预测')], default=0, verbose_name='预测结论')),
            ],
            options={
                'verbose_name': '趋势分析结果',
                'verbose_name_plural': '趋势分析结果',
            },
        ),
        migrations.DeleteModel(
            name='Analize',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
