# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0003_auto_20190427_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analizeplan',
            name='end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='analizeplan',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='analizeplan',
            name='status',
            field=models.IntegerField(choices=[(0, '待分析'), (1, '分析中'), (2, '分析完成')], default=0, verbose_name='分析状态'),
        ),
    ]
