# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0004_auto_20190427_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analizeplan',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='任务结束时间'),
        ),
    ]
